### ISSUE TITLE
can't compile the source code

### ISSUE THREAD

**Issue by deric** [anupambagchi/elki#1]
Any chance to update the Elki source code?

one of problems was fixed here:

http://elki.dbs.ifi.lmu.de/changeset/12136/elki/trunk/elki/src/main/java/de/lmu/ifi/dbs/elki/data/type/VectorTypeInformation.java

btw. how did you checkout the svn tree from trac browser?

**Comment by kno10** [comment]
The version he uploaded to github is release 0.6.0, which you could download as .jar (including the source code).

We have by now moved from svn to git, and publish an official ELKI branch at:

https://github.com/elki-project/elki

Please use this instead.

**Comment by deric** [comment]
That's great news @kno10. Github is much more friendly for reading source code :) Thanks.
